### ISSUE TITLE
Bad twiddle-wakka in metadata

### ISSUE THREAD

**Issue by cmjosh** [hardening-io/chef-apache-hardening#19]
https://github.com/hardening-io/chef-apache-hardening/blob/master/metadata.rb#L9

When trying to upload to my chef server I get:

```
E, [2015-06-02T15:01:52.801568 #76059] ERROR -- : Ridley::Errors::HTTPBadRequest: {"error":["Invalid value '~ 2.0.0' for metadata.dependencies"]}
```

I assume this ought to be ``~>`` instead?

**Comment by chris-rock** [comment]
@cmjosh I am sorry for the typo. Thank you very much for pointing this out.
